########################
# N A N O Z O O - C I T E 
# 
# Use the trace file generated by Nextflow
# to parse citations and tool versions 
# based on Docker files.
########################

OUTPUT=$1
TAG=$2

LITERATURE_DIR=${OUTPUT}/literature-${TAG}
TRACE=${OUTPUT}/trace.txt

# generate the literature bib file and versions txt
REFS=${OUTPUT}/refs.bib
VERSIONS=${OUTPUT}/versions.tsv
if test -f "$REFS"; then
    rm ${REFS}
fi
if test -f "$VERSIONS"; then
    rm ${VERSIONS}
fi
touch ${REFS}
touch ${VERSIONS}

# for each used docker container grep the literature
for TOOL in $(grep ':' ${TRACE} | awk '{print $3}' | awk 'BEGIN{FS="/"};{print $2}' | awk 'BEGIN{FS=":"};{print $1}' | uniq); do 
    
    BIB_FILE=bibs/${TOOL}.bib

    if test -f "$BIB_FILE"; then
        # write bib file to reference list
        cat ${BIB_FILE} >> ${REFS}
        cat "\n" >> ${REFS}
    fi

    # get version number 
    VERSION=$(grep ${TOOL} ${TRACE} | awk '{print $3}' | awk 'BEGIN{FS=":"};{print $2}' | awk 'BEGIN{FS="--"};{print $1}' | uniq)
    printf "$TOOL\t$VERSION\n" >> ${VERSIONS}

    # get image tag number 
    VERSION=$(grep ${TOOL} ${TRACE} | awk '{print $3}' | awk 'BEGIN{FS=":"};{print $2}' | awk 'BEGIN{FS="--"};{print $2}' | uniq)
done

